apiVersion: v1
kind: Secret
metadata:
  name: bank-dev-secrets
type: Opaque
stringData:
  YANDEX_SPRINT_10_KEYCLOAK_PASSWORD: "admin"
  YANDEX_SPRINT_10_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET: "0AU6T8CNGErz3mRskLiJ2u5Mtdud1iqz"
  YANDEX_SPRINT_10_KEYCLOAK_USER_MANAGEMENT_CLIENT_SECRET: "TleHPOuxA2JvlmhXmexYFCjgxDE4ZkIJ"
  YANDEX_SPRINT_10_ACCOUNT_POSTGRES_DB_USER_PASSWORD: "pass"
  YANDEX_SPRINT_10_CASH_POSTGRES_DB_USER_PASSWORD: "pass"
  YANDEX_SPRINT_10_TRANSFER_POSTGRES_DB_USER_PASSWORD: "pass"
  YANDEX_SPRINT_10_EXCHANGE_POSTGRES_DB_USER_PASSWORD: "pass"
